title: George Krommydas's Homepage
page-top-title: George Krommydas
top-section-bg-text: Control Systems Engineer 
home-subtitle: George Krommydas&ensp;
copyright-text: '&copy; George Krommydas 2026. All Rights Reserved.'
